[package]
name = "iroh-ping"
version = "0.7.0"
edition = "2021"
description = "high level PING-PONG iroh protocol"
license = "MIT OR Apache-2.0"
authors = ["n0 team"]
repository = "https://github.com/n0-computer/iroh-ping"
keywords = ["iroh", "protocol"]
rust-version = "1.85"

[dependencies]
anyhow = "1.0.98"
iroh = "0.95"
iroh-metrics = "0.37.0"
n0-error = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
