[package]
name = "iroh-ping"
version = "0.7.0"
edition = "2024"
description = "high level PING-PONG iroh protocol"
license = "MIT OR Apache-2.0"
authors = ["n0 team"]
repository = "https://github.com/n0-computer/iroh-ping"
keywords = ["iroh", "protocol"]
rust-version = "1.85"

[dependencies]
anyhow = "1.0.98"
iroh = "0.95"
iroh-metrics = "0.37.0"
n0-error = "0.1"

[dev-dependencies]
iroh-tickets = "0.2"
tokio = { version = "1", features = ["full"] }
tracing-subscriber = "0.3"

[patch.crates-io]
iroh = { git = "https://github.com/n0-computer/iroh", branch = "feat-multipath" }
# iroh-quinn = { git = "https://github.com/n0-computer/quinn", branch = "main-iroh" }
iroh-quinn-udp = { git = "https://github.com/n0-computer/quinn", branch = "main-iroh" }
