[package]
name = "hello-n0des"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
iroh = "0.95.1"
iroh-n0des = "0.8.0"
iroh-ping = "0.7.0"
iroh-tickets = "0.2.0"
tokio = "1.48.0"
tracing-subscriber = "0.3.22"
